language: ruby
script: 'bundle exec rake db:migrate'
#script: 'bundle exec rake db:migrate && bundle exec rspec spec/'
rvm:
  - 2.0.0
env:
notifications:
  email: 
    team@kandanapp.com
# whitelist    
branches:
  only:
    - master
