# Postgres settings
# #################
# development:
#   adapter: postgresql
#   host: localhost
#   database: kandan_development
#   pool: 5
#   timeout: 5000


#development:
#  adapter: sqlite3
#  database: db/development.sqlite3
#  pool: 5
#  timeout: 5000



development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: kandanapp_development
  pool: 5
  username: kandanapp_dev
  password: kandanapp
  host: localhost


#test:
#  adapter: sqlite3
#  database: db/test.sqlite3
#  pool: 5
#  timeout: 5000
